# Generated by Django 3.0.5 on 2020-05-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kennywoodapi', '0002_auto_20200519_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ('area',)},
        ),
    ]
